codecov:
  token: ${CODECOV_TOKEN}
  notify:
    wait_for_ci: true
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches: false
    patch:
      default:
        target: 70%
        threshold: 1%
        base: auto
        branches: false

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "Tests/"
  - ".build/"
  - "Sources/FileSystemKitCLI/"

