// FileSystemKit Core Library
// Chunk Storage Organization Protocol
//
// This file defines the protocol for organizing chunks in storage.
// Organization strategies determine how chunk identifiers map to storage paths/locations.

import Foundation

/// Protocol for organizing chunks in storage.
///
/// `ChunkStorageOrganization` defines how chunk identifiers map to storage paths/locations.
/// Clients implement this protocol to define custom organization strategies for different
/// storage backends (file system, cloud storage, databases, etc.).
///
/// ## Overview
///
/// Organization strategies determine:
/// - How chunks are organized in the storage backend
/// - Directory structure for file system backends
/// - Record naming for database backends
/// - Path generation for cloud storage backends
///
/// ## Usage
///
/// Generate storage path for a chunk:
/// ```swift
/// let organization = GitStyleOrganization(directoryDepth: 2)
/// let identifier = ChunkIdentifier(id: "a1b2c3d4e5f6...")
/// let path = organization.storagePath(for: identifier)
/// // Returns: "a1/b2/a1b2c3d4e5f6..."
/// ```
///
/// Parse identifier from path:
/// ```swift
/// let path = "a1/b2/a1b2c3d4e5f6..."
/// if let identifier = organization.identifier(from: path) {
///     print("Identifier: \(identifier.id)")
/// }
/// ```
///
/// Validate path:
/// ```swift
/// if organization.isValidPath("a1/b2/a1b2c3d4e5f6...") {
///     print("Valid path")
/// }
/// ```
///
/// ## Organization Strategies
///
/// Common strategies include:
/// - **Git-style**: Hash-based directory structure (`a1/b2/hash...`)
/// - **Flat**: All chunks in single directory (`hash...`)
/// - **CloudKit**: Record ID format (`Chunk_hash...`)
/// - **Custom**: Client-defined organization
///
/// ## See Also
///
/// - ``ChunkStorageRetrieval`` - Retrieval protocol
/// - ``ChunkStorage`` - Composed storage protocol
/// - ``GitStyleOrganization`` - Git-style hash-based organization
/// - ``FlatOrganization`` - Flat organization strategy
public protocol ChunkStorageOrganization: Sendable {
    /// Generate storage path/location for a chunk identifier.
    ///
    /// This method determines how chunks are organized in the storage backend.
    /// The path format depends on the organization strategy:
    /// - Git-style: `"a1/b2/a1b2c3d4..."` (hash-based directories)
    /// - Flat: `"a1b2c3d4..."` (single directory)
    /// - CloudKit: `"Chunk_a1b2c3d4..."` (record ID format)
    ///
    /// - Parameter identifier: Chunk identifier (typically a hash)
    /// - Returns: Storage path/location (format depends on backend)
    func storagePath(for identifier: ChunkIdentifier) -> String
    
    /// Parse chunk identifier from storage path.
    ///
    /// Reverse operation of `storagePath(for:)` - extracts identifier from path.
    /// Must be able to parse paths generated by `storagePath(for:)`.
    ///
    /// - Parameter path: Storage path/location
    /// - Returns: Chunk identifier, or nil if path is invalid
    func identifier(from path: String) -> ChunkIdentifier?
    
    /// Validate that a path is valid for this organization strategy.
    ///
    /// Checks if a path conforms to this organization strategy's format.
    /// Useful for validating paths before attempting to parse them.
    ///
    /// - Parameter path: Storage path to validate
    /// - Returns: True if path is valid for this organization strategy
    func isValidPath(_ path: String) -> Bool
    
    /// Organization strategy name/identifier.
    ///
    /// A short, unique identifier for this organization strategy.
    /// Examples: `"git-style"`, `"flat"`, `"cloudkit"`.
    var name: String { get }
    
    /// Organization strategy description.
    ///
    /// A human-readable description of how this strategy organizes chunks.
    var description: String { get }
}

